### ISSUE TITLE
Crash when exploding a monster egg block

### ISSUE THREAD

**Issue by sscards55** [Judge40/BetterMobGriefingGameRule#18]
I crashed when an explosion destroyed a silverfish moster egg. I tried a few different explosions just in case.

**Comment by sscards55** [comment]
gist with the crash reports
https://gist.github.com/sscards55/64a0eb6b8cadc7797b20e4f174d257c0

**Comment by sscards55** [comment]
I tried to replicate #17 out of curiosity and saw a similar error in the console log, but didn't get a crash from it.

**Comment by Judge40** [comment]
Thanks for the report, I'll take a look in to it.

**Comment by Judge40** [comment]
After some investigation I have found the specific part of my code triggering this issue. However, to the best of my knowledge it looks like my code is behaving as expected and something in Forge is causing an issue. Due to this I'm unfortunately not sure that I will be able to resolve it without partially removing handling for Silverfish.

I'm hoping to get a release out this week with the problematic handling removed. If I can find a way to resolve it properly then I'll do so and restore the functionality, if not then Silverfish destroying blocks when summoning allies will no longer be handled by this mod and must be done via the original mobGriefing rule.

This also applies to #17

**Comment by Judge40** [comment]
This is now fully working with version `1.12.2-7.0.0` and Forge `14.23.2.2646` or higher.
Silverfish will both spawn and be handled by the mod as expected.
